# Generated by Django 2.1.4 on 2019-01-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='liuyan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
