# Generated by Django 2.1.4 on 2018-12-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sh',
            field=models.IntegerField(choices=[(0, '未审核'), (1, '审核中'), (2, '审核完毕  ')], default=0),
        ),
    ]
