# Generated by Django 2.1.4 on 2018-12-27 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_remove_user_sh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='c',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '高级用户')], default=0, verbose_name='用户级别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='手机号不符合规范', regex='^(136)\\d{8}$')], verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户昵称'),
        ),
    ]
