# Generated by Django 2.1.4 on 2018-12-20 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pingtai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('hobby', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('realname', models.CharField(max_length=20)),
                ('sh', models.IntegerField(choices=[(0, '未审核'), (1, '审核中'), (2, '审核完毕  ')], default=0)),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
