# Generated by Django 2.1.4 on 2018-12-21 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0003_auto_20181220_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '审核管理', 'verbose_name_plural': '审核管理'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='申请时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='u_time',
            field=models.DateTimeField(auto_now=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(max_length=30, verbose_name='所在公司'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hobby',
            field=models.CharField(max_length=100, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='position',
            field=models.CharField(max_length=30, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='realname',
            field=models.CharField(max_length=20, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='reason',
            field=models.CharField(max_length=200, verbose_name='申请原因'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sh',
            field=models.IntegerField(choices=[(0, '未审核'), (1, '审核中'), (2, '审核完毕  ')], default=0, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='u',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userauth.User', verbose_name='用户昵称'),
        ),
    ]
