# Generated by Django 2.1.4 on 2018-12-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0004_auto_20181221_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptarticle',
            name='status',
            field=models.BooleanField(default=0, verbose_name='是否发表'),
        ),
    ]
